---
settings:
  name: E-Series Family
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: E-Series product family documentation
      url: /index.html
product-family:
  search: "clouddocs-e-series_main-prod,clouddocs-e-series-santricity_main-prod,clouddocs-e-series-cli_main-prod"
  sidebarlinks:
      - title: All products
        tags: tag_storage_management,tag_data_storage,tag_cli,tag_get_started,tag_SANtricity
        class: active
      - title: Get started
        tags: tag_get_started
      - title: Data storage
        tags: tag_data_storage
      - title: Storage management
        tags: tag_storage_management, tag_SANtricity

  tiles:
    - title: "Learn about the E-Series family"
      icon: ./media/groups_line-1.png
      url: intro-family.html
      summary: "Learn about the E-Series family of storage systems."
      tags: all, tag_get_started

    - title: "E-Series Systems"
      icon: ./media/system_line.png
      url: https://docs.netapp.com/us-en/e-series/index.html
      summary: "Use E-Series storage systems to support your application workloads with fast block storage and enterprise-grade reliability."
      tags: all, tag_data_storage

    - title: "SANtricity Software"
      icon: ./media/config_line.png
      url: https://docs.netapp.com/us-en/e-series-santricity/index.html
      summary: "Use SANtricity software to provision and manage your E-Series storage systems from a web-based interface."
      tags: all, tag_storage_management, tag_SANtricity

    - title: "Command Line Interface"
      icon: ./media/cli_line.png
      url: https://docs.netapp.com/us-en/trident/index.html
      summary: "Use the CLI for confguring and monitoring your E-Series storage systems from an operating system prompt."
      tags: all, tag_storage_management, tag_SANtricity
