---
settings:
  name: E-Series Family
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: E-Series and SANtricity documentation suite
      url: /index.html
product-family:
  search: "clouddocs-astra-control-service_main-prod,clouddocs-astra-control-center_main-prod,clouddocs-astra-data-store_main-prod,clouddocs-astra-automation_main-prod,clouddocs-trident_main-prod"
  sidebarlinks:
      - title: All products
        tags: tag_storage_management,tag_data_storage,tag_api,tag_get_started
        class: active
      - title: Storage management
        tags: tag_storage_management
      - title: CLI
        tags: tag_cli

  tiles:
    - title: "Learn about the E-Series family"
      icon: ./media/groups_line-1.png
      url: intro-family.html
      summary: "Learn about the E-Series family of storage systems."
      tags: all, tag_get_started

    - title: "E-Series Systems"
      icon: ./media/system_line.png
      url: https://docs.netapp.com/us-en/e-series/index.html
      summary: "Use E-Series storage systems to support your application workloads with simple, easy to manage, fast block storage with enterprise-grade reliability."
      tags: all, tag_data_storage

    - title: "SANtricity Software"
      icon: ./media/config_line.png
      url: https://docs.netapp.com/us-en/e-series-santricity/index.html
      summary: "Use SANtricity software to provision and manage your E-Series storage systems from a web-based interface."
      tags: all, tag_storage_management

    - title: "Command Line Interface"
      icon: ./media/cli_line.png
      url: https://docs.netapp.com/us-en/trident/index.html
      summary: "Use the CLI for confguring and monitoring your E-Series storage systems from an operating system prompt."
      tags: all, tag_storage_management, tag_cli
